/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(home)/': RouteRecordInfo<
      '/(home)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(home)/[...path]': RouteRecordInfo<
      '/(home)/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/[category]/[idea].[[name]]': RouteRecordInfo<
      '/[category]/[idea].[[name]]',
      '/:category/:idea/:name?',
      { category: ParamValue<true>, idea: ParamValue<true>, name?: ParamValueZeroOrOne<true> },
      { category: ParamValue<false>, idea: ParamValue<false>, name?: ParamValueZeroOrOne<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(home)/index.vue': {
      routes:
        | '/(home)/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(home)/[...path].vue': {
      routes:
        | '/(home)/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/[category]/[idea].[[name]].vue': {
      routes:
        | '/[category]/[idea].[[name]]'
      views:
        | never
      pathParamNames:
        | 'idea'
        | 'name'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
